# Change these first
owner: kphws # Your GitHub organization or username, where this repository lives
repo: dheraldlang-service-status # The name of this repository

sites:
  - name: dheraldlang.com
    url: https://dheraldlang.com/
  - name: dogonews.co.kr
    url: https://dogonews.co.kr/
  - name: herald.stest.co.kr
    url: https://herald.stest.co.kr/
  - name: stest.co.kr
    url: https://stest.co.kr/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /dheraldlang-service-status
  logoUrl: https://lms.dheraldlang.com/images/logo/logo_H_White.svg
  name: 플립언어교육 Service Status
  introTitle: "**플립언어교육** 서비스 모니터링 및 상태 페이지"
  introMessage: https://dheraldlang.com
  navbar:
    - title: 플립언어교육
      href: https://dheraldlang.com

NOTIFICATION_SLACK: true
NOTIFICATION_SLACK_WEBHOOK: true
NOTIFICATION_SLACK_WEBHOOK_URL: https://dheraldlang.com/main/upptime_notification

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
